sudo: false
language: haskell
ghc:
  - "8.2.1"
  - "7.8.4"
  - "7.6.3"
before_install:
  - cabal update
install:
  - cabal install --enable-tests --only-dependencies
script:
  - cabal configure -v --enable-tests
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
  - cabal install dist/*.tar.gz
